export const company = {
  name: 'Parkway Fabrications', phone: '0114 242 2733', phoneHref: 'tel:+441142422733',
  address: ['4 Colwall Street', 'Sheffield', 'S9 3WP', 'United Kingdom'],
  url: 'https://parkwayfabrications.co.uk'
};

export const services = [
  { slug:'laser-cutting', nav:'Laser cutting', kicker:'Precision profile cutting', title:'Fibre laser cutting in Sheffield', description:'Send a drawing for clean, repeatable profiling across steel, stainless steel, aluminium, titanium, plastics and specialist materials.', facts:['6kW fibre laser','3m interchangeable bed','Drawing-led quotation'], copy:'Parkway provides fibre laser cutting for one-off parts and repeat requirements. Share your DXF, DWG, STEP, PDF or image files with the material, thickness and quantity required; the team can assess the job and respond with a practical quotation.', process:['Drawing and specification review','Material and process assessment','Cutting and onward fabrication as required'] },
  { slug:'metal-fabrication', nav:'Metal fabrication', kicker:'From profile to assembly', title:'Metal fabrication in Sheffield', description:'A connected fabrication service for commercial buyers who need parts made from drawings, prototypes or an existing component.', facts:['Steel fabrication','Stainless steel and aluminium','One-off and repeat work'], copy:'Projects can combine cutting, folding, rolling, pressing, drilling, welding and finishing. Parkway works with engineers, manufacturers, designers and procurement teams, keeping the route from drawing to finished component clear.', process:['Review the requirement','Plan the manufacturing route','Fabricate, finish and prepare for collection or delivery'] },
  { slug:'cnc-folding', nav:'CNC folding', kicker:'Controlled bending and forming', title:'CNC folding and sheet metal bending', description:'CNC press brake folding for formed sheet-metal components, supported by fabrication processes under one roof.', facts:['4m press brake','200 tonne','Edwards Pearson CNC'], copy:'The 4m, 200 tonne Edwards Pearson CNC press brake supports folded parts and fabricated assemblies. Final material, geometry and bend feasibility are confirmed during technical review; no unsupported tolerance or thickness claims are made online.', process:['Review bend geometry','Confirm material and orientation','Fold, inspect and move to the next process'] },
  { slug:'welding', nav:'Welding', kicker:'Fabricated components and assemblies', title:'Commercial welding and fabrication', description:'Welding integrated with cutting, forming and finishing for bespoke components and repeat production requirements.', facts:['Drawing-led work','Multiple material options','Integrated fabrication'], copy:'Parkway can assess welding as part of a broader fabrication requirement. Send the assembly drawing, material, quantities and finish so the team can determine a suitable manufacturing route. Welding processes and qualifications should be confirmed directly for each project.', process:['Assess drawings and joint requirements','Confirm the fabrication sequence','Fabricate and finish to the agreed specification'] },
  { slug:'perforated-metal', nav:'Perforated metal', kicker:'Sheet and component requirements', title:'Perforated metal and perforated sheet', description:'Perforated sheet and fabricated perforated components for industrial and design applications.', facts:['Perforated sheet','Forming and fabrication','Made to requirement'], copy:'Specify the material, sheet or component dimensions, perforation requirement, quantity and finish. Parkway can review whether the requirement is for flat sheet, further forming or a completed fabricated component.', process:['Define pattern and material','Confirm component geometry','Cut, form and finish as agreed'] },
  { slug:'granulator-screens', nav:'Granulator screens', kicker:'For recycling and size reduction', title:'Replacement granulator screens', description:'Replacement screens for granulators and related recycling equipment, made against a drawing, specification or sample requirement.', facts:['Replacement screens','Recycling applications','Drawing or specification review'], copy:'A useful enquiry identifies the machine or application, material, perforation requirement, overall dimensions, quantity and urgency. Parkway will review the supplied information before confirming suitability. Machine compatibility must be verified for every order.', process:['Capture machine and screen details','Review pattern and fabrication needs','Quote against the confirmed specification'] },
  { slug:'bespoke-fabrication', nav:'Bespoke work', kicker:'A practical route through production', title:'Bespoke metal fabrication', description:'For unusual parts, replacement components and fabrication problems that do not fit a standard catalogue.', facts:['One-off requirements','Repeat production','Problem-led enquiries'], copy:'You do not need a finished CAD file to start a conversation. Share the information you have—drawing, sketch, photograph or sample details—and explain what the part needs to do. Parkway can then identify the information required to quote.', process:['Understand the function','Resolve missing specification details','Agree the manufacturing route'] }
];

export const pageMeta = {
  about:['About Parkway Fabrications | Sheffield','Learn about Parkway Fabrications and its Sheffield-based metalworking capabilities.'],
  projects:['Fabrication projects | Parkway Fabrications','A framework for verified Parkway Fabrications case studies and completed work.'],
  contact:['Contact Parkway Fabrications | Sheffield','Contact Parkway Fabrications at 4 Colwall Street, Sheffield S9 3WP or call 0114 242 2733.'],
  quote:['Request a fabrication quote | Parkway Fabrications','Upload drawings and send your laser cutting, folding, welding or fabrication requirement.']
};
