import http from 'node:http';
import { readFile, writeFile, mkdir, rename, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { extname, join, normalize } from 'node:path';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { company, services, pageMeta } from './content.js';

const PORT = Number(process.env.PORT || 3000);
const ROOT = process.cwd();
const DATA = join(ROOT, 'data');
const UPLOADS = join(ROOT, 'private-uploads');
const isProduction = process.env.DEPLOYMENT_ENV === 'production';
const allowedExt = new Set(['.dxf','.dwg','.step','.stp','.pdf','.svg','.jpg','.jpeg','.png']);
const allowedMime = new Set(['application/dxf','application/dwg','application/pdf','application/step','application/octet-stream','image/svg+xml','image/jpeg','image/png','model/step']);
const maxBody = 20 * 1024 * 1024;
const attempts = new Map();
await mkdir(DATA,{recursive:true}); await mkdir(UPLOADS,{recursive:true});

const esc = v => String(v ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugName = p => p.replace(/^\/+|\/+$/g,'') || 'home';
const canonical = p => company.url + (p === '/' ? '/' : `/${slugName(p)}/`);
const icon = `<svg class="mark" viewBox="0 0 50 50" aria-hidden="true"><path d="M3 47V3h25c12 0 19 6 19 17S40 37 28 37H15v10H3Zm12-21h12c5 0 8-2 8-6s-3-6-8-6H15v12Z"/></svg>`;

function layout({title,description,path='/',body,schema='',active=''}) {
 const robots = isProduction ? 'index, follow' : 'noindex, nofollow';
 return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="${robots}"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical(path)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical(path)}"><meta name="theme-color" content="#172019"><link rel="stylesheet" href="/styles.css">${schema}</head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Parkway Fabrications home">${icon}<span>Parkway<small>Fabrications · Sheffield</small></span></a><button class="menu" aria-expanded="false" aria-controls="nav">Menu</button><nav id="nav" aria-label="Main navigation"><a href="/services/" ${active==='services'?'aria-current="page"':''}>Capabilities</a><a href="/about/">Company</a><a href="/projects/">Projects</a><a href="/contact/">Contact</a><a class="button compact" href="/request-a-quote/">Request a quote <span>↗</span></a></nav></header><main id="main">${body}</main>${footer()}<script src="/app.js" defer></script></body></html>`;
}
function footer(){return `<footer><div class="footer-lead"><p>Have a drawing?</p><a href="/request-a-quote/">Put it in front of our team <span>↗</span></a></div><div class="footer-grid"><div class="brand">${icon}<span>Parkway<small>Fabrications · Sheffield</small></span></div><div><strong>Visit</strong><address>${company.address.map(esc).join('<br>')}</address></div><div><strong>Talk</strong><a data-event="telephone_click" href="${company.phoneHref}">${company.phone}</a></div><div><strong>Explore</strong><a href="/services/">Capabilities</a><a href="/request-a-quote/">Request a quote</a><a href="/privacy/">Privacy</a></div></div><p class="legal">© ${new Date().getFullYear()} Parkway Fabrications. Staging builds are protected from indexing.</p></footer>`}
const engineeringVisual = `<div class="engineering" aria-hidden="true"><svg viewBox="0 0 680 610"><g class="grid"><path d="M0 80h680M0 160h680M0 240h680M0 320h680M0 400h680M0 480h680M0 560h680M80 0v610M160 0v610M240 0v610M320 0v610M400 0v610M480 0v610M560 0v610M640 0v610"/></g><path class="part" d="M110 465V196l90-90h305l75 75v284H435v-92H260v92Z"/><circle cx="230" cy="214" r="38"/><circle cx="485" cy="214" r="38"/><path class="measure" d="M110 505h470m-470-12v24m470-24v24M90 196V465m-12-269h24M78 465h24"/></svg><span class="label l1">PROFILE / 001</span><span class="label l2">SHEFFIELD S9</span></div>`;

function home(){
 const body=`<section class="hero"><div class="hero-copy"><p class="eyebrow">Metalwork, resolved.</p><h1>From drawing<br>to <em>finished part.</em></h1><p class="lede">Laser cutting, CNC folding and metal fabrication from Sheffield. For exact specifications, repeat production and the jobs that need working through.</p><div class="actions"><a class="button" data-event="quote_started" href="/request-a-quote/">Upload a drawing <span>↗</span></a><a class="text-link" href="${company.phoneHref}">Or call ${company.phone}</a></div></div>${engineeringVisual}<div class="hero-index"><span>01</span><p>Parkway Fabrications<br>Sheffield, South Yorkshire</p></div></section><section class="proof-strip"><p>Manufacturing capability</p><div><strong>6kW</strong><span>Fibre laser</span></div><div><strong>3m</strong><span>Interchangeable bed</span></div><div><strong>4m · 200t</strong><span>CNC press brake</span></div></section><section class="intro"><p class="section-no">02 / Capabilities</p><div><h2>The process does not stop at the cut.</h2><p>Bring Parkway a production drawing or a fabrication problem. Cutting, folding, forming, welding and finishing can be considered as one manufacturing route—not a chain of disconnected suppliers.</p></div></section><section class="service-list">${services.map((s,i)=>`<a href="/${s.slug}/"><span>${String(i+1).padStart(2,'0')}</span><h3>${s.nav}</h3><p>${s.description}</p><b>↗</b></a>`).join('')}</section><section class="split dark"><div><p class="eyebrow">Start with what you have</p><h2>A drawing makes it fast.<br>A problem is enough.</h2></div><div><p>Upload CAD, a PDF or reference images. Add the material, quantity and required date if known. The enquiry is structured for technical review without forcing you through irrelevant questions.</p><ol><li><span>01</span>Send the requirement</li><li><span>02</span>Parkway reviews the detail</li><li><span>03</span>Receive a clear response</li></ol><a class="button light" href="/request-a-quote/">Start an enquiry <span>↗</span></a></div></section><section class="materials"><p class="section-no">03 / Materials</p><h2>Made in the material<br>the job demands.</h2><div>${['Steel','Stainless steel','Aluminium','Titanium','Plastics','Specialist materials'].map(x=>`<span>${x}</span>`).join('')}</div><p class="note">Material availability and suitability are confirmed during quotation.</p></section><section class="location"><div><p class="eyebrow">Sheffield made</p><h2>Fabrication with a<br>known address.</h2><p>Find Parkway at 4 Colwall Street, Sheffield, S9 3WP. Speak directly to the team reviewing and manufacturing your requirement.</p><a class="text-link" href="/contact/">Contact Parkway ↗</a></div><div class="mapline" aria-label="Abstract street-grid illustration of Parkway's Sheffield location"><span>53.39° N<br>1.44° W</span></div></section>`;
 const schema=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness',name:company.name,url:company.url,telephone:'+441142422733',address:{'@type':'PostalAddress',streetAddress:'4 Colwall Street',addressLocality:'Sheffield',postalCode:'S9 3WP',addressCountry:'GB'},areaServed:'United Kingdom'})}</script>`;
 return layout({title:'Laser Cutting & Metal Fabrication Sheffield | Parkway',description:'Sheffield laser cutting, CNC folding and metal fabrication. Upload a drawing or discuss a bespoke fabrication requirement with Parkway.',body,schema});
}
function servicePage(s){const body=`<div class="breadcrumb"><a href="/">Home</a><span>/</span><a href="/services/">Capabilities</a><span>/</span>${s.nav}</div><section class="page-hero"><div><p class="eyebrow">${s.kicker}</p><h1>${s.title}</h1><p class="lede">${s.description}</p><a class="button" data-event="service_cta_click" href="/request-a-quote/?service=${s.slug}">Send your requirement <span>↗</span></a></div>${engineeringVisual}</section><section class="fact-row">${s.facts.map((x,i)=>`<div><span>0${i+1}</span><strong>${x}</strong></div>`).join('')}</section><section class="content-grid"><p class="section-no">The capability</p><div><h2>Built around the requirement.</h2><p>${s.copy}</p><h3>How an enquiry moves forward</h3><ol class="process">${s.process.map((x,i)=>`<li><span>0${i+1}</span>${x}</li>`).join('')}</ol></div><aside><strong>Useful quote details</strong><ul><li>Drawing or reference files</li><li>Material and thickness</li><li>Quantity and dimensions</li><li>Finish and required date</li><li>Tolerance where relevant</li></ul></aside></section><section class="cta"><p>Ready to discuss the part?</p><h2>Send the drawing.<br>We’ll take it from there.</h2><a class="button light" href="/request-a-quote/?service=${s.slug}">Request a quote <span>↗</span></a></section>`; const schema=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Service',name:s.title,description:s.description,provider:{'@type':'LocalBusiness',name:company.name,address:'4 Colwall Street, Sheffield S9 3WP'},areaServed:'United Kingdom'})}</script>`;return layout({title:`${s.title} | Parkway Fabrications`,description:s.description,path:`/${s.slug}/`,body,schema,active:'services'});}
function servicesIndex(){return layout({title:'Metal fabrication capabilities | Parkway Fabrications',description:'Explore laser cutting, CNC folding, welding, perforated metal, granulator screens and bespoke fabrication in Sheffield.',path:'/services/',active:'services',body:`<section class="simple-hero"><p class="eyebrow">Capabilities</p><h1>One route from raw material<br>to finished component.</h1><p>Choose a specific process or send the complete requirement. Every page below is built around a distinct buyer need—not a duplicated search landing page.</p></section><section class="service-list large">${services.map((s,i)=>`<a href="/${s.slug}/"><span>${String(i+1).padStart(2,'0')}</span><h2>${s.nav}</h2><p>${s.description}</p><b>↗</b></a>`).join('')}</section>`});}
function generic(type){const [title,desc]=pageMeta[type]; const content={about:`<section class="simple-hero"><p class="eyebrow">Company</p><h1>Manufacturing support,<br>based in Sheffield.</h1><p>Parkway Fabrications provides laser cutting and connected metal fabrication processes from 4 Colwall Street, Sheffield. This first-release copy deliberately avoids unverified founding dates, accreditations and workforce claims.</p></section><section class="content-grid"><p class="section-no">What Parkway does</p><div><h2>A practical route through fabrication.</h2><p>Customers can approach Parkway with a defined drawing or an unresolved manufacturing requirement. Published capabilities include fibre laser cutting, CNC folding, welding, rolling, pressing, drilling, bending and forming, guillotine cutting, plasma cutting and finishing.</p><a class="text-link" href="/services/">Explore capabilities ↗</a></div><aside><strong>Sheffield workshop</strong><address>${company.address.join('<br>')}</address><a href="${company.phoneHref}">${company.phone}</a></aside></section>`,projects:`<section class="simple-hero"><p class="eyebrow">Verified work only</p><h1>Projects will earn<br>their place here.</h1><p>No fictional case studies, customer names or outcomes have been used. This section is ready for approved projects with a genuine brief, process, material, result and gallery.</p></section><section class="empty-state"><span>PROJECT SYSTEM / READY</span><h2>First case study pending client approval.</h2><p>Photography and project facts are required before publication.</p><a class="button" href="/request-a-quote/">Discuss your project <span>↗</span></a></section>`,contact:`<section class="simple-hero"><p class="eyebrow">Contact</p><h1>Talk to the people<br>making the part.</h1></section><section class="contact-grid"><div><span>Telephone</span><a data-event="telephone_click" href="${company.phoneHref}">${company.phone}</a></div><div><span>Workshop</span><address>${company.address.join('<br>')}</address></div><div><span>Quote</span><a href="/request-a-quote/">Upload a drawing ↗</a></div></section>`}; return layout({title,description:desc,path:`/${type}/`,body:content[type]});}

function quotePage(){const opts=services.map(s=>`<option value="${s.slug}">${s.nav}</option>`).join(''); return layout({title:pageMeta.quote[0],description:pageMeta.quote[1],path:'/request-a-quote/',body:`<section class="quote-head"><p class="eyebrow">Request a quote</p><h1>Show us what<br>you need made.</h1><p>Fields marked * are required. If you do not know every specification, leave it blank and explain the function.</p></section><form id="quote-form" enctype="multipart/form-data" novalidate><input class="hp" name="website" tabindex="-1" autocomplete="off"><fieldset><legend><span>01</span>Contact</legend><div class="fields"><label>Full name *<input name="name" required autocomplete="name"></label><label>Company *<input name="company" required autocomplete="organization"></label><label>Email *<input type="email" name="email" required autocomplete="email"></label><label>Telephone<input type="tel" name="telephone" autocomplete="tel"></label></div></fieldset><fieldset><legend><span>02</span>Requirement</legend><div class="fields"><label>Service required *<select name="service" required><option value="">Select a capability</option>${opts}<option value="other">Other / not sure</option></select></label><label>Material<select name="material"><option value="">Not yet known</option>${['Steel','Stainless steel','Aluminium','Titanium','Plastics','Specialist / other'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Thickness<input name="thickness" placeholder="e.g. 3 mm"></label><label>Quantity<input name="quantity" inputmode="numeric"></label><label class="wide">Project or manufacturing requirement *<textarea name="description" required rows="5" placeholder="Tell us what the part needs to do, relevant dimensions and processes…"></textarea></label><label>Finish<input name="finish"></label><label>Tolerance, where relevant<input name="tolerance"></label><label>Required date<input name="requiredDate" type="date"></label><label>Urgency<select name="urgency"><option>Standard</option><option>Time-sensitive</option><option>Breakdown / urgent</option></select></label></div></fieldset><fieldset><legend><span>03</span>Drawings</legend><label class="drop" id="drop"><input id="files" name="files" type="file" multiple accept=".dxf,.dwg,.step,.stp,.pdf,.svg,.jpg,.jpeg,.png"><strong>Drop files here or browse</strong><span>DXF, DWG, STEP, STP, PDF, SVG, JPG or PNG · 10 MB each · 20 MB total</span><output id="file-list"></output></label></fieldset><label class="consent"><input type="checkbox" name="consent" required> I agree that Parkway may use these details and files to respond to this enquiry. *</label><div id="form-status" role="status" aria-live="polite"></div><button class="button submit" type="submit">Send for review <span>↗</span></button></form>`});}
function privacy(){return layout({title:'Privacy notice | Parkway Fabrications',description:'How Parkway Fabrications handles website enquiries.',path:'/privacy/',body:`<article class="prose"><p class="eyebrow">Privacy</p><h1>Enquiry data</h1><p>Information submitted through this preview is used to assess and respond to fabrication enquiries. Drawing files are private and must not be placed in public asset storage.</p><h2>Production actions required</h2><p>Before launch, Parkway must approve the data controller details, lawful basis, retention periods, processor list, data-subject process and cookie/analytics configuration. The production database, object storage and mail provider must be configured under written retention and access policies.</p><p>Contact ${company.name} at ${company.address.slice(0,3).join(', ')} regarding an enquiry.</p></article>`});}

async function readBody(req){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>maxBody)throw Object.assign(new Error('Request too large'),{status:413});chunks.push(c)}return Buffer.concat(chunks)}
function rateOK(ip){const now=Date.now(), row=(attempts.get(ip)||[]).filter(t=>now-t<3600000);if(row.length>=10)return false;row.push(now);attempts.set(ip,row);return true}
async function saveEnquiry(req,res){const ip=req.socket.remoteAddress||'unknown';if(!rateOK(ip))return json(res,429,{error:'Too many enquiries. Please call us instead.'});let payload;try{payload=JSON.parse((await readBody(req)).toString())}catch(e){return json(res,e.status||400,{error:e.status?'Files are too large.':'The request could not be read.'})}if(payload.website)return json(res,200,{ok:true,reference:'PF-RECEIVED'});const required=['name','company','email','service','description','consent'];if(required.some(k=>!payload[k])||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(payload.email))return json(res,422,{error:'Please complete all required fields with a valid email.'});const files=Array.isArray(payload.files)?payload.files:[];let total=0,saved=[];for(const f of files){const ext=extname(f.name||'').toLowerCase(), mime=(f.type||'').toLowerCase(),buf=Buffer.from(f.data||'','base64');total+=buf.length;if(!allowedExt.has(ext)||!allowedMime.has(mime)||buf.length>10*1024*1024||total>20*1024*1024)return json(res,422,{error:'A file type or size is not allowed.'});const key=randomBytes(20).toString('hex')+ext;await writeFile(join(UPLOADS,key),buf,{mode:0o600});saved.push({originalName:String(f.name).slice(0,180),key,mime,size:buf.length})}const records=await loadRecords();const sequence=records.length+1,reference=`PF-${new Date().getUTCFullYear()}-${String(sequence).padStart(6,'0')}`;records.push({reference,status:'NEW',createdAt:new Date().toISOString(),contact:{name:String(payload.name).slice(0,120),company:String(payload.company).slice(0,160),email:String(payload.email).slice(0,200),telephone:String(payload.telephone||'').slice(0,50)},requirement:Object.fromEntries(['service','material','thickness','quantity','description','finish','tolerance','requiredDate','urgency'].map(k=>[k,String(payload[k]||'').slice(0,k==='description'?5000:300)])),files:saved});await atomicRecords(records);console.info(JSON.stringify({event:'enquiry_created',reference,fileCount:saved.length}));return json(res,201,{ok:true,reference});}
async function loadRecords(){try{return JSON.parse(await readFile(join(DATA,'enquiries.json'),'utf8'))}catch{return []}}
async function atomicRecords(x){const tmp=join(DATA,`.enquiries-${process.pid}.tmp`);await writeFile(tmp,JSON.stringify(x,null,2),{mode:0o600});await rename(tmp,join(DATA,'enquiries.json'))}
function authenticated(req){const auth=req.headers.authorization||'';if(!auth.startsWith('Basic '))return false;const [u,p]=Buffer.from(auth.slice(6),'base64').toString().split(':');const eu=process.env.ADMIN_USER||'parkway',hash=process.env.ADMIN_PASSWORD_HASH;if(!hash||u!==eu)return false;const [salt,want]=hash.split(':');const got=scryptSync(p,salt,32);return want&&timingSafeEqual(got,Buffer.from(want,'hex'))}
async function admin(req,res,path){if(!authenticated(req)){res.writeHead(401,{'WWW-Authenticate':'Basic realm="Parkway admin"','X-Robots-Tag':'noindex, nofollow'});return res.end('Authentication required')}const records=await loadRecords();if(path==='/admin/api/enquiries')return json(res,200,records.map(({files,...x})=>({...x,fileCount:files.length})));const body=`<section class="admin"><p class="eyebrow">Secure admin</p><h1>Enquiries</h1><div class="admin-tools"><input id="admin-search" placeholder="Search reference, company or contact"><select id="admin-filter"><option value="">All statuses</option>${['NEW','CONTACTED','QUOTED','WON','LOST','ARCHIVED'].map(x=>`<option>${x}</option>`).join('')}</select></div><div id="enquiries" data-records="${esc(JSON.stringify(records))}">${records.length?'Loading…':'No enquiries yet.'}</div></section>`;return html(res,200,layout({title:'Enquiries | Parkway Admin',description:'Private enquiry management.',path:'/admin/',body}))}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function html(res,status,data){res.writeHead(status,{'Content-Type':'text/html; charset=utf-8'});res.end(data)}
async function staticFile(res,path){const safe=normalize(path).replace(/^(\.\.[/\\])+/,''),file=join(ROOT,'public',safe);if(!file.startsWith(join(ROOT,'public')))return false;try{const s=await stat(file);if(!s.isFile())return false;const types={'.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':'public, max-age=3600'});createReadStream(file).pipe(res);return true}catch{return false}}

export const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),path=url.pathname;const headers={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self' 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'self'",'X-Frame-Options':'DENY','Cross-Origin-Opener-Policy':'same-origin','X-Robots-Tag':isProduction?'index, follow':'noindex, nofollow'};for(const[k,v]of Object.entries(headers))res.setHeader(k,v);if(path.startsWith('/admin'))return admin(req,res,path);if(req.method==='POST'&&path==='/api/enquiries')return saveEnquiry(req,res);if(path==='/robots.txt'){res.setHeader('Content-Type','text/plain');return res.end(isProduction?'User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: https://parkwayfabrications.co.uk/sitemap.xml\n':'User-agent: *\nDisallow: /\n')}if(path==='/sitemap.xml'){res.setHeader('Content-Type','application/xml');const urls=['/',...services.map(s=>`/${s.slug}/`),'/services/','/about/','/projects/','/contact/','/request-a-quote/'];return res.end(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${canonical(x)}</loc></url>`).join('')}</urlset>`)}if(await staticFile(res,path.slice(1)))return;let page;if(path==='/')page=home();else if(path==='/services/'||path==='/services')page=servicesIndex();else{const s=services.find(x=>path===`/${x.slug}/`||path===`/${x.slug}`);if(s)page=servicePage(s);else if(/^\/(about|projects|contact)\/?$/.test(path))page=generic(path.split('/')[1]);else if(/^\/request-a-quote\/?$/.test(path))page=quotePage();else if(/^\/privacy\/?$/.test(path))page=privacy()}if(page)return html(res,200,page);return html(res,404,layout({title:'Page not found | Parkway Fabrications',description:'The requested page could not be found.',path,body:'<section class="simple-hero"><p class="eyebrow">404</p><h1>That part is not<br>in this assembly.</h1><a class="button" href="/">Return home ↗</a></section>'}))}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:'Something went wrong. Please try again or call 0114 242 2733.'})}});
if(process.env.NODE_ENV!=='test')server.listen(PORT,()=>console.log(`Parkway preview: http://localhost:${PORT}`));
